spring:
  profiles: dev
    active: 
    - dev
--- 
server:
  port: 8020
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka-dev.com:7001/eureka/
--- 
server:
  port: 8021
spring:
  profiles: test
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka-test.com:7001/eureka/
