spring:
   profiles:
   active: -dev

---
spring:
   profiles: dev    #测试环境ks
   application: 
      name: user-config-client
server:
    port: 3355
eureka:
   client:
      service-url:
         defaultZone: http://root:root@eureka-test.com:7001/eureka/

---
spring:
   profiles: test    #测试环境
   application: 
      name: user-config-client
server:
    port: 7777
eureka:
   client:
      service-url:
         defaultZone: http://root:root@eureka-test.com:7001/eureka/
